.PHONY: clean All

All:
	@echo "----------Building project:[ Anodisation - Release ]----------"
	@cd "Anodisation" && "$(MAKE)" -f  "Anodisation.mk"
clean:
	@echo "----------Cleaning project:[ Anodisation - Release ]----------"
	@cd "Anodisation" && "$(MAKE)" -f  "Anodisation.mk" clean
