.PHONY: clean All

All:
	@echo "----------Building project:[ Multi_fenetre - Debug ]----------"
	@cd "Multi_fenetre" && "$(MAKE)" -f  "Multi_fenetre.mk"
clean:
	@echo "----------Cleaning project:[ Multi_fenetre - Debug ]----------"
	@cd "Multi_fenetre" && "$(MAKE)" -f  "Multi_fenetre.mk" clean
