.PHONY: clean All

All:
	@echo "----------Building project:[ Serveur_de_communication - Release ]----------"
	@cd "Test_serveur" && "$(MAKE)" -f  "Serveur_de_communication.mk"
clean:
	@echo "----------Cleaning project:[ Serveur_de_communication - Release ]----------"
	@cd "Test_serveur" && "$(MAKE)" -f  "Serveur_de_communication.mk" clean
