.PHONY: clean All

All:
	@echo "----------Building project:[ Test_serveur - Debug ]----------"
	@cd "Test_serveur" && "$(MAKE)" -f  "Test_serveur.mk"
clean:
	@echo "----------Cleaning project:[ Test_serveur - Debug ]----------"
	@cd "Test_serveur" && "$(MAKE)" -f  "Test_serveur.mk" clean
