.PHONY: clean All

All:
	@echo "----------Building project:[ Test_serveur - Release ]----------"
	@cd "Serveur/Test_serveur" && "$(MAKE)" -f  "Test_serveur.mk"
clean:
	@echo "----------Cleaning project:[ Test_serveur - Release ]----------"
	@cd "Serveur/Test_serveur" && "$(MAKE)" -f  "Test_serveur.mk" clean
