#ifndef __EvtFramePrincipal__
#define __EvtFramePrincipal__

/**
@file
Subclass of FramePrincipal, which is generated by wxFormBuilder.
*/

#include "FramePrincipal.h"

//// end generated include
/*******************************************************************************
*  Fichier:  EvtFramePrincipal.h
*  Projet:
*  Crée le:  //2018
*  Utilité:  Gestion des événements du frame principal
*  Auteur:   Florian Provost
*******************************************************************************/
#include "DataAnnodisation.h"
#include "Client.h"
class Client;
#define ID_CLIENT 100

#include "Protocole.h"
#include "Client.h"
class Client;
#include <wx/log.h>
#include <iostream>
#include <string>
using std::string;
#include <vector>
using std::vector;
/** Implementing FramePrincipal */
class EvtFramePrincipal : public FramePrincipal
{
	protected:
		// Handlers for FramePrincipal events.
		void OnFrameClose( wxCloseEvent& event );
		void OnButtonConnexionToggle( wxCommandEvent& event );
		void OnButtonChoixTrajectoiresClicks( wxCommandEvent& event );
		void OnButtonChoixMouvementsClicks( wxCommandEvent& event );
		void OnListBoxAffichageSelectionMouvements( wxCommandEvent& event );
		void OnListBoxModifierSelectionMouvements( wxCommandEvent& event );
		void OnApplyButtonModifierMouvementClick( wxCommandEvent& event );
		void OnCancelButtonModifierMouvementClick( wxCommandEvent& event );
		void OnSaveButtonCreerMouvementClick( wxCommandEvent& event );
		void OnListBoxDetruireSelectionMouvements( wxCommandEvent& event );
		void OnYesButtonDetruireMouvementClick( wxCommandEvent& event );
		void OnListBoxTesterSelectionMouvements( wxCommandEvent& event );
		void OnYesButtonTesterMouvementClick( wxCommandEvent& event );
		void OnListBoxAffichageSelectionTrajectoires( wxCommandEvent& event );
		void OnListBoxModifierSelectionTrajectoires( wxCommandEvent& event );
		void OnApplyButtonModifierTrajectoiresClick( wxCommandEvent& event );
		void OnCancelButtonModifierTrajectoiresClick( wxCommandEvent& event );
		void OnListBoxSelectionMouvementsCreationTrajectoire( wxCommandEvent& event );
		void OnSaveButtonCreerTrajectoiresClick( wxCommandEvent& event );
		void OnListBoxDetruireSelectionTrajectoires( wxCommandEvent& event );
		void OnYesButtonDetruireTrajectoiresClick( wxCommandEvent& event );
		void OnListBoxTesterSelectionTrajectoires( wxCommandEvent& event );
		void OnYesButtonTesterTrajectoiresClick( wxCommandEvent& event );
		void OnButtonViderAffichageClick( wxCommandEvent& event );
	public:
		/** Constructor */
		EvtFramePrincipal( wxWindow* parent );
	//// end generated class members
    private:
        Client *m_client;
        DataAnodisation *m_bdd_anodisation;
        bool m_bdd_connecte;
        bool m_client_connecte;
        bool m_identifie;
        bool VerificationLogin(wxString login, wxString pass);
        void AfficheStatus(wxString texte, int position);
        void RempliListBoxMouvements();
        void RempliListBoxTrajectoires();
        //void RempliListBoxMouvementsModifierTrajectoires();
        wxString GardeIdSelection(wxString texte);
        void VideListBoxMouvements();
        void VideListBoxTrajectoires();
        void DeconnexionClient(wxString message);
    protected:
        void AfficheInfoClient(wxCommandEvent& event);
        void AfficheMessageClient(wxCommandEvent& event);
        void AgitServeurPerdu(wxCommandEvent& event);

    public:
        string ConversionEnString(wxString texte);
        wxString ConversionEnWxString(string texte);
        wxString DecouperTexteDebut(wxString texte, int position);
        wxString DecouperTexteFin(wxString texte, int position);



};

#endif // __EvtFramePrincipal__
