#ifndef __EvtFramePrincipal__
#define __EvtFramePrincipal__

/**
@file
Subclass of FramePrincipal, which is generated by wxFormBuilder.
*/

#include "FramePrincipal.h"

//// end generated include
/*******************************************************************************
  *  Fichier:  EvtFramePrincipal.h
  *  Projet:   
  *  Crée le:  //2018
  *  Utilité:  Gestion des événements du frame principal
  *  Auteur:   Florian Provost
*******************************************************************************/

/** Implementing FramePrincipal */
class EvtFramePrincipal : public FramePrincipal
{
	protected:
		// Handlers for FramePrincipal events.
		void OnFrameClose( wxCloseEvent& event );
		void OnMenuQuitterSelection( wxCommandEvent& event );
		void OnMenuAideSelection( wxCommandEvent& event );
		void OnMenuAproposSelection( wxCommandEvent& event );
	public:
		/** Constructor */
		EvtFramePrincipal( wxWindow* parent );
	//// end generated class members
    private:
        
    protected:
        
    public:
        
};

#endif // __EvtFramePrincipal__
