#ifndef __EvtDialogTest__
#define __EvtDialogTest__

/**
@file
Subclass of DialogTest, which is generated by wxFormBuilder.
*/

#include "FramePrincipal.h"

//// end generated include
/*******************************************************************************
*  Fichier:  EvtDialogTest.h
*  Projet:   Chaîne d'anodisation - Test d'IHM
*  Crée le:  14/04/2018
*  Utilité:  Gestion des événements du dialog test
*  Auteur:   Florian Provost
*******************************************************************************/

/** Implementing DialogTest */
class EvtDialogTest : public DialogTest
{
	protected:
		// Handlers for DialogTest events.
		void OnFrameClose( wxCloseEvent& event );
		void OnClickButtonCancel( wxCommandEvent& event );
		void OnClickButtonOK( wxCommandEvent& event );
	public:
		/** Constructor */
		EvtDialogTest( wxWindow* parent );
	//// end generated class members








};

#endif // __EvtDialogTest__
