#ifndef __EvtMyDialogApropos__
#define __EvtMyDialogApropos__

/**
@file
Subclass of MyDialogApropos, which is generated by wxFormBuilder.
*/

#include "FramePrincipal.h"

//// end generated include
/*******************************************************************************
*  Fichier:  EvtDialogApropos.h
*  Projet:   Chaîne d'anodisation - Test d'IHM
*  Crée le:  15/04/2018
*  Utilité:  Gestion des événements du dialog à propos
*  Auteur:   Florian Provost
*******************************************************************************/

/** Implementing MyDialogApropos */
class EvtMyDialogApropos : public MyDialogApropos
{
	protected:
		// Handlers for MyDialogApropos events.
		void OnFrameClose( wxCloseEvent& event );
		void OnClickButtonOK( wxCommandEvent& event );
	public:
		/** Constructor */
		EvtMyDialogApropos( wxWindow* parent );
	//// end generated class members






};

#endif // __EvtMyDialogApropos__
