#ifndef __EvtFramePrincipal__
#define __EvtFramePrincipal__

/**
@file
Subclass of FramePrincipal, which is generated by wxFormBuilder.
*/

#include "FramePrincipal.h"

//// end generated include
#include "./Client.h"
class Client;
#include <wx/log.h>
#include <iostream>

#define ID_CLIENT 100

/** Implementing FramePrincipal */
class EvtFramePrincipal : public FramePrincipal
{
    protected:
        // Handlers for FramePrincipal events.
        void OnButtonConnexionToggle(wxCommandEvent& event);
        void OnClickButtonSaisie(wxCommandEvent& event);
    public:
        /** Constructor */
        EvtFramePrincipal(wxWindow* parent);
        //// end generated class members
    protected:
        void ConnexionServeur(wxCommandEvent& event);
        
        void Execution(wxCommandEvent& event);
        void Erreur(wxCommandEvent& event);
        void Information(wxCommandEvent& event);
        void GereReponse(wxString reponse, wxString reponse_attendue);
        void OnFrameClose(wxCloseEvent& event) ;
    private:
        void Deconnexion(wxString reponse);
        Client *m_client;
        bool m_connecte;
};

#endif // __EvtFramePrincipal__
