#ifndef __EvtFramePrincipal__
#define __EvtFramePrincipal__

/**
@file
Subclass of FramePrincipal, which is generated by wxFormBuilder.
*/

#include "FramePrincipal.h"
//// end generated include
/*******************************************************************************
*  Fichier:  EvtFramePrincipal.h
*  Projet:   Chaîne d'anodisation - Gestion du client BdD pour le PC du
responsable de production
*  Crée le:  29/04/2018
*  Utilité:  Gestion des événements du frame principal
*  Auteur:   Florian Provost
*******************************************************************************/
#include "EvtMyDialogAide.h"
#include "DataAnodisation.h"

/** Implementing FramePrincipal */
class EvtFramePrincipal : public FramePrincipal
{
	protected:
		// Handlers for FramePrincipal events.
		void OnFrameClose( wxCloseEvent& event );
		void OnToggleButtonConnexion( wxCommandEvent& event );
		void OnButtonClickSelection( wxCommandEvent& event );
		void OnButtonClickInsertion( wxCommandEvent& event );
		void OnButtonClickMAJ( wxCommandEvent& event );
		void OnButtonClickSuppression( wxCommandEvent& event );
		void OnMenuQuitterSelection( wxCommandEvent& event );
		void OnMenuAideSelection( wxCommandEvent& event );
	public:
		/** Constructor */
		EvtFramePrincipal( wxWindow* parent );
	//// end generated class members
    private:
        DataAnodisation* m_bdd_anodisation;
        void AfficheStatus(wxString texte, int position);
        void AfficheResultat(wxString texte);
};

#endif // __EvtFramePrincipal__
