#ifndef __EvtMyDialogAide__
#define __EvtMyDialogAide__

/**
@file
Subclass of MyDialogAide, which is generated by wxFormBuilder.
*/

#include "FramePrincipal.h"

//// end generated include
/*******************************************************************************
*  Fichier:  EvtMyDialogAide.h
*  Projet:   Chaîne d'anodisation - Gestion du client BdD pour le PC du
responsable de production
*  Crée le:  29/04/2018
*  Utilité:  Gestion des événements de la boite de dialogue aide
*  Auteur:   Florian Provost
*******************************************************************************/

/** Implementing MyDialogAide */
class EvtMyDialogAide : public MyDialogAide
{
	protected:
		// Handlers for MyDialogAide events.
		void OnDialogClose( wxCloseEvent& event );
		void OnOKButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		EvtMyDialogAide( wxWindow* parent );
	//// end generated class members




};

#endif // __EvtMyDialogAide__
