#ifndef __EvtMyDialogAide__
#define __EvtMyDialogAide__

/**
@file
Subclass of MyDialogAide, which is generated by wxFormBuilder.
*/

#include "FramePrincipal.h"

//// end generated include

/** Implementing MyDialogAide */
class EvtMyDialogAide : public MyDialogAide
{
	protected:
		// Handlers for MyDialogAide events.
		void OnOKButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		EvtMyDialogAide( wxWindow* parent );
	//// end generated class members



};

#endif // __EvtMyDialogAide__
