#ifndef __guiMainFrameBase__
#define __guiMainFrameBase__

/**
@file
Subclass of MainFrameBase, which is generated by wxFormBuilder.
*/

#include "gui.h"

//// end generated include

/** Implementing MainFrameBase */
class guiMainFrameBase : public MainFrameBase
{
	protected:
		// Handlers for MainFrameBase events.
		void OnCloseFrame( wxCloseEvent& event );
		void OnExitClick( wxCommandEvent& event );
	public:
		/** Constructor */
		guiMainFrameBase( wxWindow* parent );
	//// end generated class members
	
};

#endif // __guiMainFrameBase__
