#ifndef __EvtFramePrincipal__
#define __EvtFramePrincipal__

/**
@file
Subclass of FramePrincipal, which is generated by wxFormBuilder.
*/

#include "FramePrincipal.h"
#include "AccesI2C.h"

//// end generated include

/** Implementing FramePrincipal */
class EvtFramePrincipal : public FramePrincipal
{
	public:
		/** Constructor */
		EvtFramePrincipal( wxWindow* parent );
	//// end generated class members
	
    private:
        AccesI2C *I2C;
};

#endif // __EvtFramePrincipal__
