/*********************************************************************
 * Nom:         EvtFramePrincipal.h
 * purpose:     definir les methodes et attribut d'EvtFramePrincipal.cpp
 * Author :     Nassim Boubziz à l'énorme TEUB!!! ZBEUB ZBEUB
 * Created:     29/11/2017
*********************************************************************/
#ifndef __EvtFramePrincipal__
#define __EvtFramePrincipal__

/**
@file
Subclass of FramePrincipal, which is generated by wxFormBuilder.
*/

#include "FramePrincipal.h"

//// end generated include
/** Implementing FramePrincipal */
class EvtFramePrincipal : public FramePrincipal
{
	public:
		/** Constructor */
		EvtFramePrincipal( wxWindow* parent );
	//// end generated class members
	private:
};

#endif // __EvtFramePrincipal__
