.PHONY: clean All

All:
	@echo "----------Building project:[ Regleur - Debug ]----------"
	@cd "Regleur" && "$(MAKE)" -f  "Regleur.mk"
clean:
	@echo "----------Cleaning project:[ Regleur - Debug ]----------"
	@cd "Regleur" && "$(MAKE)" -f  "Regleur.mk" clean
