.PHONY: clean All

All:
	@echo "----------Building project:[ Acces_BdD - Debug ]----------"
	@cd "Acces_BdD" && "$(MAKE)" -f  "Acces_BdD.mk"
clean:
	@echo "----------Cleaning project:[ Acces_BdD - Debug ]----------"
	@cd "Acces_BdD" && "$(MAKE)" -f  "Acces_BdD.mk" clean
