.PHONY: clean All

All:
	@echo "----------Building project:[ Responsable_production - Debug ]----------"
	@cd "Responsable_production" && "$(MAKE)" -f  "Responsable_production.mk"
clean:
	@echo "----------Cleaning project:[ Responsable_production - Debug ]----------"
	@cd "Responsable_production" && "$(MAKE)" -f  "Responsable_production.mk" clean
