/*********************************************************************
 * Nom:         EvtFramePrincipal.h
 * purpose:     definir les methodes et attribut d'EvtFramePrincipal.cpp
 * Author :     Nassim Boubziz 
 * Created:     29/11/2017
*********************************************************************/
#ifndef __EvtFramePrincipal__
#define __EvtFramePrincipal__

/**
@file
Subclass of FramePrincipal, which is generated by wxFormBuilder.
*/

#include "FramePrincipal.h"

//// end generated includ
class Client;
#define ID_CLIENT 100
/** Implementing FramePrincipal */
class EvtFramePrincipal : public FramePrincipal
{
	public:
    
    EvtFramePrincipal( wxWindow* parent );
protected:
	void OnButtonConnexionToggle( wxCommandEvent& event );
	void OnButtonMajusculeClick( wxCommandEvent& event );
	void OnButtonMinusculeClick( wxCommandEvent& event );
    void OnFrameClose( wxCloseEvent& event ) ;

    /*voir a rajouter des evenements */
    void GereReponse(wxString reponse, wxString reponse_attendue);
		/** Constructor */
		EvtFramePrincipal( wxWindow* parent );
	//// end generated class members
public:
    Client *m_client;
    bool m_connecte;
    void Dconnexion(wxString message);
protected:
    void ConnexionServeur(wxCommandEvent& event);
    void EnvoiReception(wxCommandEvent& event);
    void Execution(wxCommandEvent& event);
    void Erreur(wxCommandEvent& event);
    void Information(wxCommandEvent& event);
    void Deconnexion(wxCommandEvent& event)
	private:
    Client *m_client;
    bool m_connecte;
    void Dconnexion(wxString message);
};

#endif // __EvtFramePrincipal__
