/*********************************************************************
 * Nom:         EvtFramePrincipal.h
 * purpose:     definir les methodes et attribut d'EvtFramePrincipal.cpp
 * Author :     Nassim Boubziz 
 * Created:     29/11/2017
*********************************************************************/
#ifndef __EvtFramePrincipal__
#define __EvtFramePrincipal__

/**
@file
Subclass of FramePrincipal, which is generated by wxFormBuilder.
*/
#define ID_CLIENT ???
#include "FramePrincipal.h"
class Client;
//// end generated includ
/** Implementing FramePrincipal */
class EvtFramePrincipal : public FramePrincipal
{
	public:
    Client *m_client;
    bool m_connecte;
    void Dconnexion(wxString message);
    EvtFramePrincipal( wxWindow* parent );
protected:
	void OnButtonConnexionToggle( wxCommandEvent& event );
	void OnButtonMajusculeClick( wxCommandEvent& event );
	void OnButtonMinusculeClick( wxCommandEvent& event );
    void OnFrameClose( wxCloseEvent& event ) ;
    void /**/ (wxCommandEvent& event);
    void /**/ (wxCommandEvent& event);
    void /**/ (wxCommandEvent& event);
    /*voir a rajouter des evenements */
    void GereReponse(wxString reponse, wxString reponse_attendue);
		/** Constructor */
		EvtFramePrincipal( wxWindow* parent );
	//// end generated class members
	private:
    Client *m_client;
    bool m_connecte;
    void Dconnexion(wxString message);
};

#endif // __EvtFramePrincipal__
