#ifndef __EvtFrameAide__
#define __EvtFrameAide__

/**
@file
Subclass of FrameAide, which is generated by wxFormBuilder.
*/

#include "FramePrincipal.h"

//// end generated include

/** Implementing FrameAide */
class EvtFrameAide : public FrameAide
{
	protected:
		// Handlers for FrameAide events.
		void OnCloseFrame( wxCloseEvent& event );
		void OnOkButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		EvtFrameAide( wxWindow* parent );
	//// end generated class members
    
};

#endif // __EvtFrameAide__
