#ifndef __EvtFrameApropos__
#define __EvtFrameApropos__

/**
@file
Subclass of FrameApropos, which is generated by wxFormBuilder.
*/

#include "FramePrincipal.h"

//// end generated include

/** Implementing FrameApropos */
class EvtFrameApropos : public FrameApropos
{
	protected:
		// Handlers for FrameApropos events.
		void OnCloseFrame( wxCloseEvent& event );
		void OnOkButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		EvtFrameApropos( wxWindow* parent );
	//// end generated class members
    
};

#endif // __EvtFrameApropos__
