#ifndef __EvtFrameApropos__
#define __EvtFrameApropos__

/**
@file
Subclass of FrameApropos, which is generated by wxFormBuilder.
*/

#include "FramePrincipal.h"

//// end generated include
/*******************************************************************************
*  Fichier:  EvtFrameApropos.h
*  Projet:   Chaîne d'anodisation - Gestion du PC responsable de production
*  Crée le:  15/05/2018
*  Utilité:  Gestion des événements du frame à propos
*  Auteur:   Florian Provost
*******************************************************************************/

/** Implementing FrameApropos */
class EvtFrameApropos : public FrameApropos
{
	protected:
		// Handlers for FrameApropos events.
		void OnCloseFrame( wxCloseEvent& event );
		void OnOkButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		EvtFrameApropos( wxWindow* parent );
	//// end generated class members



};

#endif // __EvtFrameApropos__
