#ifndef __EvtPanelRegleur__
#define __EvtPanelRegleur__

/**
@file
Subclass of PanelRegleur, which is generated by wxFormBuilder.
*/

#include "PanelRegleur.h"

//// end generated include

/** Implementing PanelRegleur */
class EvtPanelRegleur : public PanelRegleur
{
	protected:
		// Handlers for PanelRegleur events.
		void OnListBoxAffichageSelectionMouvements( wxCommandEvent& event );
		void OnListBoxModifierSelectionMouvements( wxCommandEvent& event );
		void OnApplyButtonModifierMouvementClick( wxCommandEvent& event );
		void OnCancelButtonModifierMouvementClick( wxCommandEvent& event );
		void OnSaveButtonCreerMouvementClick( wxCommandEvent& event );
		void OnListBoxDetruireSelectionMouvements( wxCommandEvent& event );
		void OnYesButtonDetruireMouvementClick( wxCommandEvent& event );
		void OnListBoxTesterSelectionMouvements( wxCommandEvent& event );
		void OnCancelButtonTestMouvementClick( wxCommandEvent& event );
		void OnInfoBrasTestMouvementClick( wxCommandEvent& event );
		void OnYesButtonTesterMouvementClick( wxCommandEvent& event );
		void OnListBoxAffichageSelectionTrajectoires( wxCommandEvent& event );
		void OnListBoxModifierSelectionTrajectoires( wxCommandEvent& event );
		void OnApplyButtonModifierTrajectoiresClick( wxCommandEvent& event );
		void OnCancelButtonModifierTrajectoiresClick( wxCommandEvent& event );
		void OnListBoxSelectionMouvementsCreationTrajectoire( wxCommandEvent& event );
		void OnSaveButtonCreerTrajectoiresClick( wxCommandEvent& event );
		void OnListBoxDetruireSelectionTrajectoires( wxCommandEvent& event );
		void OnYesButtonDetruireTrajectoiresClick( wxCommandEvent& event );
		void OnListBoxTesterSelectionTrajectoires( wxCommandEvent& event );
		void OnCancelButtonTestTrajectoireClick( wxCommandEvent& event );
		void OnInfoBrasTestTrajectoireClick( wxCommandEvent& event );
		void OnYesButtonTesterTrajectoiresClick( wxCommandEvent& event );
	public:
		/** Constructor */
		EvtPanelRegleur( wxWindow* parent );
	//// end generated class members


};

#endif // __EvtPanelRegleur__
