#ifndef __EvtPanelResponsable__
#define __EvtPanelResponsable__

/**
@file
Subclass of PanelResponsable, which is generated by wxFormBuilder.
*/

#include "PanelResponsable.h"

//// end generated include

/** Implementing PanelResponsable */
class EvtPanelResponsable : public PanelResponsable
{
	protected:
		// Handlers for PanelResponsable events.
		void OnCharEntered( wxKeyEvent& event );
		void OnListBoxAffichageSelection( wxCommandEvent& event );
		void OnTextMaxLength( wxCommandEvent& event );
		void OnCharEnteredNum( wxKeyEvent& event );
		void OnListBoxModifierSelection( wxCommandEvent& event );
		void OnApplyButtonModifierClick( wxCommandEvent& event );
		void OnCharEnteredOrdre( wxKeyEvent& event );
		void OnSpinCtrlModifierBain( wxSpinEvent& event );
		void OnCancelButtonModiffierClick( wxCommandEvent& event );
		void OnSaveButtonCreerClick( wxCommandEvent& event );
		void OnSpinCtrlCreerBain( wxSpinEvent& event );
		void OnCancelButtonCreerClick( wxCommandEvent& event );
		void OnListBoxDetruireSelection( wxCommandEvent& event );
		void OnApplyButtonDetruireClick( wxCommandEvent& event );
		void OnListBoxLancerSelection( wxCommandEvent& event );
		void OnOkButtonLancerClick( wxCommandEvent& event );
		void OnListBoxTesterSelection( wxCommandEvent& event );
		void OnStopButtonTesterClick( wxCommandEvent& event );
		void OnOkButtonTesterClick( wxCommandEvent& event );
		void OnButtonDisponibiliteBrasClick( wxCommandEvent& event );
		void OnButtonTacheEnCoursClick( wxCommandEvent& event );
	public:
		/** Constructor */
		EvtPanelResponsable( wxWindow* parent );
	//// end generated class members


};

#endif // __EvtPanelResponsable__
