#ifndef __EvtPannelBainCreer__
#define __EvtPannelBainCreer__

/**
@file
Subclass of PannelBainCreer, which is generated by wxFormBuilder.
*/

#include "PannelBainCreer.h"

//// end generated include

/** Implementing PannelBainCreer */
class EvtPannelBainCreer : public PannelBainCreer
{
	public:
		/** Constructor */
		EvtPannelBainCreer( wxWindow* parent );
	//// end generated class members



};

#endif // __EvtPannelBainCreer__
