#ifndef __EvtPannelBainModifier__
#define __EvtPannelBainModifier__

/**
@file
Subclass of PannelBainModifier, which is generated by wxFormBuilder.
*/

#include "PannelBainModifier.h"

//// end generated include

/** Implementing PannelBainModifier */
class EvtPannelBainModifier : public PannelBainModifier
{
	public:
		/** Constructor */
		EvtPannelBainModifier( wxWindow* parent );
	//// end generated class members


};

#endif // __EvtPannelBainModifier__
