.PHONY: clean All

All:
	@echo "----------Building project:[ Test_requete_avec_affichage_et_saisie - Debug ]----------"
	@cd "Test_requete_avec_affichage_et_saisie" && "$(MAKE)" -f  "Test_requete_avec_affichage_et_saisie.mk"
clean:
	@echo "----------Cleaning project:[ Test_requete_avec_affichage_et_saisie - Debug ]----------"
	@cd "Test_requete_avec_affichage_et_saisie" && "$(MAKE)" -f  "Test_requete_avec_affichage_et_saisie.mk" clean
