#ifndef __EvtDialogApropos__
#define __EvtDialogApropos__

/**
@file
Subclass of DialogApropos, which is generated by wxFormBuilder.
*/

#include "FramePrincipal.h"

//// end generated include
/*******************************************************************************
*  Fichier:  EvtDialogApropos.h
*  Projet:   Chaîne d'anodisation - Gestion du PC responsable de production
*  Crée le:  13/05/2018
*  Utilité:  Gestion des événements de la boite de dialogue À propos
*  Auteur:   Florian Provost
*******************************************************************************/

/** Implementing DialogApropos */
class EvtDialogApropos : public DialogApropos
{
	protected:
		// Handlers for DialogApropos events.
		void OnDialogClose( wxCloseEvent& event );
		void OnOkButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		EvtDialogApropos( wxWindow* parent );
	//// end generated class members






};

#endif // __EvtDialogApropos__
