#ifndef __EvtDialogAide__
#define __EvtDialogAide__

/**
@file
Subclass of DialogAide, which is generated by wxFormBuilder.
*/

#include "FramePrincipal.h"

//// end generated include
/*******************************************************************************
*  Fichier:  EvtDialogAide.h
*  Projet:   Chaîne d'anodisation - Gestion du PC responsable de production
*  Crée le:  13/05/2018
*  Utilité:  Gestion des événements de la boite de dialogue aide
*  Auteur:   Florian Provost
*******************************************************************************/

/** Implementing DialogAide */
class EvtDialogAide : public DialogAide
{
	protected:
		// Handlers for DialogAide events.
		void OnDialogClose( wxCloseEvent& event );
		void OnOkButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		EvtDialogAide( wxWindow* parent );
	//// end generated class members


};

#endif // __EvtDialogAide__
