#ifndef __EvtFrameAide__
#define __EvtFrameAide__

/**
@file
Subclass of FrameAide, which is generated by wxFormBuilder.
*/

#include "FramePrincipal.h"

//// end generated include
/*******************************************************************************
  *  Fichier:  EvtFrameAide.h
  *  Projet:   Chaîne d'anodisation - Gestion du PC responsable de production
  *  Crée le:  15/05/2018
  *  Utilité:  Gestion des événements du frame aide
  *  Auteur:   Florian Provost
*******************************************************************************/

/** Implementing FrameAide */
class EvtFrameAide : public FrameAide
{
	protected:
		// Handlers for FrameAide events.
		void OnCloseFrame( wxCloseEvent& event );
		void OnOkButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		EvtFrameAide( wxWindow* parent );
	//// end generated class members
	
};

#endif // __EvtFrameAide__
